### ISSUE TITLE
NPCs erased when updating from 1.x.x -> 2.3.3 -> 2.4.X

### ISSUE THREAD

**Issue by rekurse-dev** [Eisi05/NpcApi-Spigot#33]
### Description

I first updated from 1.x.x to 2.3.3, it worked perfectly fine but I updated the server to 26.2, so I installed the 2.4.1 version and the NPCs just disappear and corrupt. same happens when updating from 2.3.3 to 3.x.x

here's the log:
[19:44:36 INFO]: [NpcPlugin-Paper] Loading NpcApi...[19:44:37 WARN]: [NpcPlugin-Paper] Task #64 for NpcPlugin-Paper v3.3.2 generated an exceptionjava.lang.NoClassDefFoundError: org/yaml/snakeyaml/external/biz/base64Coder/Base64Coder at NpcPlugin-Paper-3.3.2-all.jar//de.eisi05.npc.api.utils.serialize.ItemSerializer.itemStackFromBase64(ItemSerializer.java:40) ~[?:?] at NpcPlugin-Paper-3.3.2-all.jar//de.eisi05.npc.api.objects.NpcOption.lambda$static$20(NpcOption.java:278) ~[?:?] at java.base/java.util.HashMap.forEach(HashMap.java:1430) ~[?:?] at NpcPlugin-Paper-3.3.2-all.jar//de.eisi05.npc.api.objects.NpcOption.lambda$static$21(NpcOption.java:264) ~[?:?] at NpcPlugin-Paper-3.3.2-all.jar//de.eisi05.npc.api.objects.NpcOption.deserialize(NpcOption.java:1012) ~[?:?] at NpcPlugin-Paper-3.3.2-all.jar//de.eisi05.npc.api.objects.NPC$SerializedNPC.lambda$deserializedNPC$2(NPC.java:1660) ~[?:?] at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?] at NpcPlugin-Paper-3.3.2-all.jar//de.eisi05.npc.api.objects.NPC$SerializedNPC.lambda$deserializedNPC$3(NPC.java:1660) ~[?:?] at java.base/java.util.HashMap.forEach(HashMap.java:1430) ~[?:?] at NpcPlugin-Paper-3.3.2-all.jar//de.eisi05.npc.api.objects.NPC$SerializedNPC.lambda$deserializedNPC$4(NPC.java:1658) ~[?:?] at java.base/java.util.HashMap.forEach(HashMap.java:1430) ~[?:?] at NpcPlugin-Paper-3.3.2-all.jar//de.eisi05.npc.api.objects.NPC$SerializedNPC.deserializedNPC(NPC.java:1657) ~[?:?] at NpcPlugin-Paper-3.3.2-all.jar//de.eisi05.npc.api.manager.NpcManager.loadNPCs(NpcManager.java:164) ~[?:?] at NpcPlugin-Paper-3.3.2-all.jar//de.eisi05.npc.api.NpcApi.<init>(NpcApi.java:73) ~[?:?] at NpcPlugin-Paper-3.3.2-all.jar//de.eisi05.npc.api.NpcApi.createInstance(NpcApi.java:106) ~[?:?] at NpcPlugin-Paper-3.3.2-all.jar//de.eisi05.npc.plugin.listeners.ServerReadyListener$1.run(ServerReadyListener.java:24) ~[?:?] at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[paper-26.2.jar:26.2-123-5001879] at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:474) ~[paper-26.2.jar:26.2-123-5001879] at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1767) ~[paper-26.2.jar:26.2-123-5001879] at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1620) ~[paper-26.2.jar:26.2-123-5001879] at net.minecraft.server.dedicated.DedicatedServer.tickServer(DedicatedServer.java:404) ~[paper-26.2.jar:26.2-123-5001879] at net.minecraft.server.MinecraftServer.processPacketsAndTick(MinecraftServer.java:1678) ~[paper-26.2.jar:26.2-123-5001879] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1348) ~[paper-26.2.jar:26.2-123-5001879] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303) ~[paper-26.2.jar:26.2-123-5001879] at java.base/java.lang.Thread.run(Thread.java:1474) ~[?:?]Caused by: java.lang.ClassNotFoundException: org.yaml.snakeyaml.external.biz.base64Coder.Base64Coder at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:146) ~[paper-26.2.jar:26.2-123-5001879] at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:107) ~[paper-26.2.jar:26.2-123-5001879] at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:490) ~[?:?] ... 25 more

### Server Software

- [ ] Spigot
- [x] Paper
- [ ] Other

### Server Version

26.2

### Plugin/API Version

2.4.x and above

### Using API/Plugin

- [ ] Using NpcAPI as a dependency
- [ ] Using NpcAPI as a plugin
- [ ] Both

### Steps to Reproduce

1. update from 1.x.x to 2.3.3
2. update from 2.3.3 to 2.4.x or above

### Expected Behavior

the plugin should seamlessly read the legacy Base64 asset layout, translate the compressed entities, and load old characters back into active memory space without breaking runtime processes

### Actual Behavior

all NPCs disappeared completely (files corrupted) except for one (swapped skin, disabled, commands still preserved, etc.)

### Error Logs

```text
[19:44:36 INFO]: [NpcPlugin-Paper] Loading NpcApi...
[19:44:37 WARN]: [NpcPlugin-Paper] Task #64 for NpcPlugin-Paper v3.3.2 generated an exception
java.lang.NoClassDefFoundError: org/yaml/snakeyaml/external/biz/base64Coder/Base64Coder
        at NpcPlugin-Paper-3.3.2-all.jar//de.eisi05.npc.api.utils.serialize.ItemSerializer.itemStackFromBase64(ItemSerializer.java:40) ~[?:?]
        at NpcPlugin-Paper-3.3.2-all.jar//de.eisi05.npc.api.objects.NpcOption.lambda$static$20(NpcOption.java:278) ~[?:?]
        ...
Caused by: java.lang.ClassNotFoundException: org.yaml.snakeyaml.external.biz.base64Coder.Base64Coder
        at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:146) ~[paper-26.2.jar:26.2-123-5001879]
```

### Screenshots/Videos

<img width="2560" height="1080" alt="Image" src="https://github.com/user-attachments/assets/2905e3cf-5c07-48ee-8c9e-0758fcaa1e40" />

**Comment by rekurse-dev** [comment]
@Eisi05

**Comment by rekurse-dev** [comment]
(happens on Paper, just to clarify)

**Comment by Eisi05** [comment]
Resolved with version 3.3.3.

This issue only occurred with 26.2. If you first updated from, for example, 2.x.x to 3.3.2 while still on version 26.1, and then updated from 26.1 to 26.2, everything works as expected.

Version 3.3.3 should handle this case, so you can update the plugin and the server version at the same time.
